import type { Company, CompanyData } from "./types";

export const ORG_NAME = "DDS Group";

export const COMPANIES: Company[] = [
  {
    id: "occ",
    code: "OCC",
    name: "Obesity Care Clinic",
    brandVoice: "warm, professional, evidence-based",
    accent: "#2563eb",
  },
  {
    id: "tibok",
    code: "TI",
    name: "Tibok",
    brandVoice: "friendly, modern, accessible",
    accent: "#d62976",
  },
  {
    id: "cvmi",
    code: "CV",
    name: "Cabo Verde Medical International",
    brandVoice: "authoritative, international, medical",
    accent: "#16a34a",
  },
];

const occ: CompanyData = {
  dashboard: {
    organic: { scheduled: 7, published7d: 12, inLibrary: 23, failed: 1 },
    paid: {
      activeCampaigns: 3,
      spendMtd: 2840,
      spendCap: 5000,
      conversions: 142,
      aiBudgetUsed: 8,
      aiBudgetCap: 65,
    },
    upcomingPosts: [
      { platform: "facebook", title: "Hydration wellness tip", when: "Mon 09:00" },
      { platform: "instagram", title: "Hydration wellness tip", when: "Mon 09:00" },
      { platform: "facebook", title: "Sarah's journey", when: "Wed 09:00" },
    ],
    topAd: {
      platform: "facebook",
      name: "Hydration tip — FB Feed",
      spend: 420,
      ctr: "3.8%",
      conversions: 34,
    },
  },
  accounts: [
    { id: "occ-fb", platform: "facebook", accountName: "OCC Facebook Page", status: "active" },
    { id: "occ-ig", platform: "instagram", accountName: "@occ_mauritius", status: "active" },
  ],
  scheduled: [
    { id: "s1", platform: "facebook", title: "Hydration wellness tip", date: "2026-05-25", time: "09:00", source: "automation", automationName: "M/W/F wellness tips", media: { kind: "image" }, body: "Staying hydrated isn't just about quenching thirst — it supports metabolism, focus, and recovery. Aim for 2L a day." },
    { id: "s2", platform: "instagram", title: "Hydration wellness tip", date: "2026-05-25", time: "09:00", source: "automation", automationName: "M/W/F wellness tips", media: { kind: "image" }, body: "Hydration check! Your body uses water for everything — digestion, focus, even skin glow.\n\n#wellness #hydration" },
    { id: "s3", platform: "facebook", title: "Patient testimonial — Sarah", date: "2026-05-27", time: "09:00", source: "automation", automationName: "Patient stories", body: "Sarah lost 18kg over 14 months with our supervised program.\n\n\"The team supported me every step of the way.\" — Read her full story." },
    { id: "s4", platform: "facebook", title: "Free consultation week — May promo", date: "2026-05-27", time: "15:30", source: "manual", media: { kind: "image" }, body: "This week only: book a free initial consultation with our specialists. Limited slots — reserve yours today." },
    { id: "s5", platform: "instagram", title: "Weekly wellness tip — sleep", date: "2026-05-29", time: "09:00", source: "automation", automationName: "M/W/F wellness tips", body: "Quality sleep is the foundation of a healthy metabolism. Aim for 7–9 hours and keep a consistent schedule.\n\n#sleep #wellness" },
    { id: "d1", platform: "facebook", title: "Bariatric Q&A — answering your questions", date: "2026-05-30", time: "10:00", source: "manual", status: "draft", body: "We get a lot of questions about bariatric surgery. This week our team answers the most common ones — from recovery time to long-term results." },
    { id: "d2", platform: "instagram", title: "Meet the team — Dr. Patel", date: "2026-06-01", time: "12:00", source: "manual", status: "draft", body: "Say hello to Dr. Patel, who has guided hundreds of patients through their weight-loss journey with warmth and evidence-based care." },
    { id: "d3", platform: "facebook", title: "June challenge — 10K steps a day", date: "2026-06-02", time: "08:00", source: "manual", status: "draft", body: "This June, join our 10,000-steps-a-day challenge. Small daily movement adds up to big results — who's in?" },
  ],
  library: {
    unused: 23,
    runway: "~2.5 wks",
    aiBudgetUsed: 8.4,
    aiBudgetCap: 65,
    imageSpend: 8.4,
    videoSpend: 0,
    templates: [
      {
        id: "t1",
        platform: "facebook",
        tags: ["wellness", "hydration"],
        body: "Staying hydrated isn't just about quenching thirst — it supports metabolism, focus, and recovery.",
        status: "unused",
        addedDate: "2026-05-18",
        media: { kind: "image", ready: true },
      },
      {
        id: "t2",
        platform: "instagram",
        tags: ["wellness"],
        body: "Hydration check! Your body uses water for everything — digestion, focus, even skin glow. #wellness",
        status: "used",
        addedDate: "2026-05-12",
        media: { kind: "image", ready: true },
      },
      {
        id: "t3",
        platform: "facebook",
        tags: ["testimonials"],
        body: "Sarah lost 18kg over 14 months with our supervised program.",
        status: "unused",
        addedDate: "2026-05-20",
        media: { kind: "none", ready: false },
      },
      {
        id: "t4",
        platform: "instagram",
        tags: ["tips", "wellness"],
        body: "Small swap, big difference: replace one sugary drink a day with water. #wellness",
        status: "used",
        addedDate: "2026-05-09",
        media: { kind: "video", seconds: 5, ready: true },
      },
      {
        id: "t5",
        platform: "facebook",
        tags: ["education"],
        body: "Understanding BMI is a starting point, not the whole story. Our specialists look at the full picture of your health.",
        status: "unused",
        addedDate: "2026-05-21",
        media: { kind: "none", ready: false },
      },
      {
        id: "t6",
        platform: "instagram",
        tags: ["recipes"],
        body: "High-protein breakfast idea: Greek yoghurt, berries, and a sprinkle of seeds. Keeps you full for hours.",
        status: "archived",
        addedDate: "2026-04-28",
        media: { kind: "image", ready: true },
      },
    ],
  },
  automations: {
    active: 2,
    paused: 1,
    postsThisWeek: 6,
    rules: [
      {
        id: "a1",
        name: "OCC Facebook — M/W/F wellness tips",
        account: "OCC Facebook",
        socialAccountId: "occ-fb",
        platform: "facebook",
        days: ["mon", "wed", "fri"],
        time: "09:00",
        libraryName: "OCC Facebook library",
        tagFilter: ["wellness"],
        onEmpty: "pause_and_alert",
        schedule: "Mon, Wed, Fri at 09:00",
        status: "active",
        libraryNote: "Library: wellness (12 unused)",
        next: "Mon 25 May 09:00",
        last: "Fri 22 May 09:00",
        publishedCount: 47,
        lastRunAt: "2026-05-22T09:00:00",
        enabled: true,
      },
      {
        id: "a2",
        name: "OCC Instagram — M/W/F wellness tips",
        account: "OCC Instagram",
        socialAccountId: "occ-ig",
        platform: "instagram",
        days: ["mon", "wed", "fri"],
        time: "09:00",
        libraryName: "OCC Instagram library",
        tagFilter: ["wellness"],
        onEmpty: "pause_and_alert",
        schedule: "Mon, Wed, Fri at 09:00",
        status: "library_low",
        libraryNote: "3 unused — 1 week left",
        publishedCount: 22,
        warning: "Library empty after Fri 29 May. Add templates to keep running.",
        enabled: true,
      },
      {
        id: "a3",
        name: "OCC Facebook — patient testimonials",
        account: "OCC Facebook",
        socialAccountId: "occ-fb",
        platform: "facebook",
        days: ["fri"],
        time: "14:00",
        libraryName: "OCC Facebook library",
        tagFilter: ["testimonials"],
        onEmpty: "pause_and_alert",
        schedule: "Every Friday at 14:00",
        status: "paused",
        libraryNote: "",
        publishedCount: 11,
        pausedSince: "Paused since 18 May",
        enabled: false,
      },
    ],
  },
  history: [
    {
      id: "h1",
      platform: "instagram",
      body: "Hydration check! Your body uses water...",
      when: "Fri 22 May 09:00",
      source: "automation",
      status: "published",
      stats: "3 comments",
    },
    {
      id: "h2",
      platform: "facebook",
      body: "Staying hydrated isn't just about quenching...",
      when: "Fri 22 May 09:00",
      source: "automation",
      status: "published",
      stats: "124 reactions · 8 comments",
    },
    {
      id: "h3",
      platform: "instagram",
      body: "Small swap, big difference...",
      when: "Wed 20 May 09:00",
      source: "automation",
      status: "failed",
      error: {
        title: "Image dimensions invalid for Instagram",
        detail: 'Meta: "Aspect ratio must be between 4:5 and 1.91:1. Provided: 2.1:1." Crop before reposting.',
      },
    },
    {
      id: "h4",
      platform: "facebook",
      body: "Small swap, big difference...",
      when: "Wed 20 May 09:00",
      source: "automation",
      status: "published",
      stats: "89 reactions · 5 comments",
    },
  ],
  campaigns: {
    activeCampaigns: 3,
    spendMtd: 2840,
    conversions: 142,
    avgCpc: 0.42,
    list: [
      {
        id: "c1",
        name: "January Detox Program — Lead Gen",
        objective: "Leads",
        platforms: ["FB", "IG"],
        status: "active",
        spend: 1200,
        budget: 2000,
        metricsLabel: "48,210 impr.",
        metricsValue: "2.97% CTR · 89 leads",
        cplLabel: "EUR 13.48 CPL",
        enabled: true,
        adSets: [
          {
            id: "as1",
            name: "Women 35-55 Mauritius",
            placement: "FB Feed + IG Feed + IG Stories",
            targeting: "Lookalike: OCC patients",
            ads: 3,
            dailyBudget: 40,
          },
          {
            id: "as2",
            name: "Men 35-55 Mauritius",
            placement: "FB Feed + IG Feed",
            targeting: "Interests: fitness, health",
            ads: 2,
            dailyBudget: 40,
          },
        ],
      },
      {
        id: "c2",
        name: "Wellness Webinar — Awareness",
        objective: "Awareness",
        platforms: ["IG"],
        status: "active",
        spend: 640,
        budget: 1500,
        metricsLabel: "124,800 impr.",
        metricsValue: "1 set · 2 ads",
        enabled: true,
        adSets: [],
      },
      {
        id: "c3",
        name: "Bariatric Consultation — Conversions",
        objective: "Conversions",
        platforms: ["FB"],
        status: "active",
        spend: 1000,
        budget: 3000,
        metricsLabel: "53 conv.",
        metricsValue: "EUR 18.87 CPA",
        enabled: true,
        adSets: [],
      },
    ],
  },
  audiences: {
    total: 7,
    inUse: 4,
    combinedReach: "~480K",
    list: [
      {
        id: "aud1",
        type: "saved",
        name: "Women 35-55 Mauritius — Wellness",
        description: "Female · 35-55 · Mauritius",
        detail: "Interests: weight loss, wellness, nutrition",
        reach: "180K-220K",
        created: "Created 12 May",
        inUse: 2,
      },
      {
        id: "aud2",
        type: "saved",
        name: "Men 35-55 Mauritius — Health",
        description: "Male · 35-55 · Mauritius",
        detail: "Interests: fitness, men's health",
        reach: "140K-170K",
        created: "Created 12 May",
        inUse: 1,
      },
      {
        id: "aud3",
        type: "custom",
        name: "OCC past patients",
        description: "Uploaded list · 1,247 matched on Meta",
        detail: "Refreshed 18 May",
        reach: "~1.2K",
        created: "Created 28 Apr",
        inUse: 1,
      },
      {
        id: "aud4",
        type: "lookalike",
        name: "Lookalike — OCC patients (1%)",
        description: "Mauritius · Top 1% similarity",
        detail: "Based on OCC past patients",
        reach: "~12K",
        created: "Created 28 Apr",
        inUse: 1,
      },
    ],
  },
  adPerformance: {
    spend: 2840,
    spendTrend: "UP 12%",
    impressions: "205K",
    impressionsTrend: "UP 8%",
    clicks: "6,720",
    clicksTrend: "UP 15%",
    conversions: 142,
    conversionsTrend: "UP 22%",
    avgCpc: 0.42,
    avgCpcTrend: "DN 3%",
    series: {
      spend: [40, 62, 70, 78, 82, 80, 88, 96, 104, 118, 126, 132],
      conversions: [18, 24, 28, 30, 34, 33, 40, 44, 50, 56, 62, 70],
    },
    topAds: [
      { name: "Hydration tip — FB Feed", context: "January Detox · Women 35-55", spend: 420, ctr: "3.8%", cpc: 0.38, conv: 34 },
      { name: "Patient testimonial — IG Stories", context: "January Detox · Lookalike", spend: 380, ctr: "3.2%", cpc: 0.41, conv: 28 },
      { name: "Free consultation — FB Feed", context: "Bariatric · Men 40-60", spend: 520, ctr: "2.1%", cpc: 0.55, conv: 22 },
    ],
    insight:
      '"Hydration tip" is your best performer at EUR 12.35 per conversion. Consider increasing its budget by 30%, or testing similar messaging in other campaigns.',
  },
  adSafety: {
    monthlyCap: 5000,
    usedThisMonth: 2840,
    requireBudgetCap: true,
    confirmAiSpend: true,
    doubleConfirmThreshold: 500,
    dailyDigest: true,
    recentAudit: 'Younes increased "January Detox" daily budget EUR 60 to 80 · 21 May 15:42',
  },
};

const tibok: CompanyData = {
  dashboard: {
    organic: { scheduled: 4, published7d: 9, inLibrary: 15, failed: 0 },
    paid: {
      activeCampaigns: 2,
      spendMtd: 1420,
      spendCap: 4000,
      conversions: 96,
      aiBudgetUsed: 14,
      aiBudgetCap: 65,
    },
    upcomingPosts: [
      { platform: "instagram", title: "Telehealth in 60 seconds", when: "Tue 10:00" },
      { platform: "facebook", title: "Meet your doctor online", when: "Thu 11:00" },
    ],
    topAd: {
      platform: "instagram",
      name: "Consult from home — IG Reels",
      spend: 310,
      ctr: "4.1%",
      conversions: 41,
    },
  },
  accounts: [
    { id: "ti-fb", platform: "facebook", accountName: "Tibok Facebook Page", status: "active" },
    { id: "ti-ig", platform: "instagram", accountName: "@tibok.health", status: "active" },
  ],
  scheduled: [
    { id: "ts1", platform: "instagram", title: "Telehealth in 60 seconds", date: "2026-05-26", time: "10:00", source: "automation", automationName: "Daily education", media: { kind: "video" }, body: "Feeling unwell? Talk to a licensed doctor from your couch in minutes.\n\n#telehealth" },
    { id: "ts2", platform: "facebook", title: "Meet your doctor online", date: "2026-05-28", time: "11:00", source: "manual", needsReview: true, media: { kind: "image" }, body: "No waiting rooms. No traffic. Just quality care, online — whenever you need it." },
    { id: "ts3", platform: "instagram", title: "5 signs you should see a GP", date: "2026-05-30", time: "10:00", source: "automation", automationName: "Daily education", body: "When should you actually see a doctor? Here are 5 signs not to ignore." },
    { id: "td1", platform: "instagram", title: "How online prescriptions work", date: "2026-05-31", time: "10:00", source: "manual", status: "draft", body: "Wondering how online prescriptions work with Tibok? Here's the simple 3-step process — consult, get your script, collect at your pharmacy." },
    { id: "td2", platform: "facebook", title: "Weekend clinic hours update", date: "2026-06-01", time: "09:00", source: "manual", status: "draft", body: "Good news — our online doctors are now available all weekend. Quality care whenever you need it, no appointment required." },
  ],
  library: {
    unused: 15,
    runway: "~1.8 wks",
    aiBudgetUsed: 14.2,
    aiBudgetCap: 65,
    imageSpend: 11.0,
    videoSpend: 3.2,
    templates: [
      {
        id: "tb1",
        platform: "instagram",
        tags: ["education", "telehealth"],
        body: "Feeling unwell? Talk to a licensed doctor from your couch in minutes. #telehealth",
        status: "unused",
        addedDate: "2026-05-19",
        media: { kind: "image", ready: true },
      },
      {
        id: "tb2",
        platform: "facebook",
        tags: ["education"],
        body: "No waiting rooms. No traffic. Just quality care, online.",
        status: "used",
        addedDate: "2026-05-10",
        media: { kind: "image", ready: true },
      },
      {
        id: "tb3",
        platform: "instagram",
        tags: ["tips"],
        body: "When should you actually see a doctor? Here are 5 signs not to ignore.",
        status: "unused",
        addedDate: "2026-05-22",
        media: { kind: "video", seconds: 8, ready: true },
      },
      {
        id: "tb4",
        platform: "facebook",
        tags: ["trust"],
        body: "Every Tibok doctor is fully licensed and verified. Your health is in safe hands.",
        status: "used",
        addedDate: "2026-05-06",
        media: { kind: "none", ready: false },
      },
    ],
  },
  automations: {
    active: 1,
    paused: 1,
    postsThisWeek: 3,
    rules: [
      {
        id: "tba1",
        name: "Tibok Instagram — daily education",
        account: "Tibok Instagram",
        socialAccountId: "ti-ig",
        platform: "instagram",
        days: ["mon", "tue", "wed", "thu", "fri"],
        time: "10:00",
        libraryName: "Tibok Instagram library",
        tagFilter: ["education"],
        onEmpty: "pause_and_alert",
        schedule: "Mon-Fri at 10:00",
        status: "active",
        libraryNote: "Library: education (9 unused)",
        next: "Tue 26 May 10:00",
        last: "Mon 25 May 10:00",
        publishedCount: 62,
        lastRunAt: "2026-05-25T10:00:00",
        enabled: true,
      },
      {
        id: "tba2",
        name: "Tibok Facebook — weekly trust posts",
        account: "Tibok Facebook",
        socialAccountId: "ti-fb",
        platform: "facebook",
        days: ["mon"],
        time: "11:00",
        libraryName: "Tibok Facebook library",
        tagFilter: ["trust"],
        onEmpty: "pause_and_alert",
        schedule: "Every Monday at 11:00",
        status: "paused",
        libraryNote: "",
        publishedCount: 8,
        pausedSince: "Paused since 11 May",
        enabled: false,
      },
    ],
  },
  history: [
    {
      id: "th1",
      platform: "instagram",
      body: "Feeling unwell? Talk to a licensed doctor...",
      when: "Mon 25 May 10:00",
      source: "automation",
      status: "published",
      stats: "212 reactions · 14 comments",
    },
    {
      id: "th2",
      platform: "facebook",
      body: "No waiting rooms. No traffic...",
      when: "Sat 23 May 09:00",
      source: "manual",
      status: "published",
      stats: "58 reactions · 2 comments",
    },
  ],
  campaigns: {
    activeCampaigns: 2,
    spendMtd: 1420,
    conversions: 96,
    avgCpc: 0.36,
    list: [
      {
        id: "tc1",
        name: "Telehealth Launch — Traffic",
        objective: "Traffic",
        platforms: ["FB", "IG"],
        status: "active",
        spend: 820,
        budget: 1500,
        metricsLabel: "92,400 impr.",
        metricsValue: "3.4% CTR · 41 conv",
        cplLabel: "EUR 20.00 CPA",
        enabled: true,
        adSets: [
          {
            id: "tas1",
            name: "Adults 25-45 Mauritius",
            placement: "FB Feed + IG Reels",
            targeting: "Interests: healthcare, busy professionals",
            ads: 3,
            dailyBudget: 30,
          },
        ],
      },
      {
        id: "tc2",
        name: "App Installs — Mobile",
        objective: "App promotion",
        platforms: ["IG"],
        status: "paused",
        spend: 600,
        budget: 1200,
        metricsLabel: "61,200 impr.",
        metricsValue: "1 set · 2 ads",
        enabled: false,
        adSets: [],
      },
    ],
  },
  audiences: {
    total: 4,
    inUse: 2,
    combinedReach: "~310K",
    list: [
      {
        id: "tau1",
        type: "saved",
        name: "Busy professionals 25-45",
        description: "All · 25-45 · Mauritius",
        detail: "Interests: healthcare, productivity",
        reach: "150K-190K",
        created: "Created 8 May",
        inUse: 1,
      },
      {
        id: "tau2",
        type: "lookalike",
        name: "Lookalike — Tibok app users (2%)",
        description: "Mauritius · Top 2% similarity",
        detail: "Based on app installers",
        reach: "~24K",
        created: "Created 2 May",
        inUse: 1,
      },
    ],
  },
  adPerformance: {
    spend: 1420,
    spendTrend: "UP 9%",
    impressions: "112K",
    impressionsTrend: "UP 18%",
    clicks: "3,980",
    clicksTrend: "UP 21%",
    conversions: 96,
    conversionsTrend: "UP 31%",
    avgCpc: 0.36,
    avgCpcTrend: "DN 6%",
    series: {
      spend: [22, 30, 36, 40, 44, 48, 52, 58, 60, 66, 70, 74],
      conversions: [10, 14, 18, 20, 26, 30, 38, 44, 52, 60, 70, 82],
    },
    topAds: [
      { name: "Consult from home — IG Reels", context: "Telehealth Launch · 25-45", spend: 310, ctr: "4.1%", cpc: 0.31, conv: 41 },
      { name: "No waiting rooms — FB Feed", context: "Telehealth Launch · 25-45", spend: 280, ctr: "3.3%", cpc: 0.38, conv: 29 },
    ],
    insight:
      '"Consult from home" reels are converting 32% above account average. Reels placement is outperforming feed — consider shifting more budget there.',
  },
  adSafety: {
    monthlyCap: 4000,
    usedThisMonth: 1420,
    requireBudgetCap: true,
    confirmAiSpend: true,
    doubleConfirmThreshold: 400,
    dailyDigest: true,
    recentAudit: 'Younes paused "App Installs — Mobile" · 19 May 11:08',
  },
};

const cvmi: CompanyData = {
  dashboard: {
    organic: { scheduled: 2, published7d: 5, inLibrary: 9, failed: 0 },
    paid: {
      activeCampaigns: 1,
      spendMtd: 560,
      spendCap: 3000,
      conversions: 18,
      aiBudgetUsed: 3,
      aiBudgetCap: 65,
    },
    upcomingPosts: [
      { platform: "facebook", title: "International patient program", when: "Wed 12:00" },
      { platform: "facebook", title: "Accredited care, global standards", when: "Fri 12:00" },
    ],
    topAd: {
      platform: "facebook",
      name: "Medical excellence — FB Feed",
      spend: 240,
      ctr: "2.4%",
      conversions: 12,
    },
  },
  accounts: [
    { id: "cv-fb", platform: "facebook", accountName: "CVMI Facebook Page", status: "active" },
  ],
  scheduled: [
    { id: "cs1", platform: "facebook", title: "International patient program", date: "2026-05-27", time: "12:00", source: "automation", automationName: "Twice-weekly trust posts", media: { kind: "image" }, body: "Our international patient program coordinates travel, treatment, and recovery — all in one place." },
    { id: "cs2", platform: "facebook", title: "Accredited care, global standards", date: "2026-05-29", time: "12:00", source: "manual", body: "Internationally accredited care, delivered with precision and compassion. World-class medicine, close to home." },
    { id: "cd1", platform: "facebook", title: "Patient travel guide — what to expect", date: "2026-05-31", time: "12:00", source: "manual", status: "draft", body: "Travelling for treatment can feel daunting. Our patient travel guide walks you through every step, from visa support to recovery accommodation." },
  ],
  library: {
    unused: 9,
    runway: "~3.0 wks",
    aiBudgetUsed: 3.1,
    aiBudgetCap: 65,
    imageSpend: 3.1,
    videoSpend: 0,
    templates: [
      {
        id: "cv1",
        platform: "facebook",
        tags: ["trust"],
        body: "Internationally accredited care, delivered with precision and compassion.",
        status: "unused",
        addedDate: "2026-05-15",
        media: { kind: "image", ready: true },
      },
      {
        id: "cv2",
        platform: "facebook",
        tags: ["programs"],
        body: "Our international patient program coordinates travel, treatment, and recovery — all in one place.",
        status: "used",
        addedDate: "2026-05-08",
        media: { kind: "image", ready: true },
      },
      {
        id: "cv3",
        platform: "facebook",
        tags: ["trust"],
        body: "Specialists trained across three continents. World-class medicine, close to home.",
        status: "unused",
        addedDate: "2026-05-16",
        media: { kind: "none", ready: false },
      },
    ],
  },
  automations: {
    active: 1,
    paused: 0,
    postsThisWeek: 2,
    rules: [
      {
        id: "cva1",
        name: "CVMI Facebook — twice-weekly trust posts",
        account: "CVMI Facebook",
        socialAccountId: "cv-fb",
        platform: "facebook",
        days: ["wed", "fri"],
        time: "12:00",
        libraryName: "CVMI Facebook library",
        tagFilter: ["trust"],
        onEmpty: "pause_and_alert",
        schedule: "Wed, Fri at 12:00",
        status: "active",
        libraryNote: "Library: trust (6 unused)",
        next: "Wed 27 May 12:00",
        last: "Fri 22 May 12:00",
        publishedCount: 28,
        lastRunAt: "2026-05-22T12:00:00",
        enabled: true,
      },
    ],
  },
  history: [
    {
      id: "ch1",
      platform: "facebook",
      body: "Internationally accredited care...",
      when: "Fri 22 May 12:00",
      source: "automation",
      status: "published",
      stats: "41 reactions · 1 comment",
    },
    {
      id: "ch2",
      platform: "facebook",
      body: "Specialists trained across three continents...",
      when: "Wed 20 May 12:00",
      source: "automation",
      status: "published",
      stats: "33 reactions",
    },
  ],
  campaigns: {
    activeCampaigns: 1,
    spendMtd: 560,
    conversions: 18,
    avgCpc: 0.61,
    list: [
      {
        id: "cvc1",
        name: "International Patients — Awareness",
        objective: "Awareness",
        platforms: ["FB"],
        status: "active",
        spend: 560,
        budget: 2000,
        metricsLabel: "38,900 impr.",
        metricsValue: "2.4% CTR · 18 conv",
        cplLabel: "EUR 31.11 CPA",
        enabled: true,
        adSets: [
          {
            id: "cvas1",
            name: "Regional — West Africa 30-60",
            placement: "FB Feed",
            targeting: "Interests: medical travel, healthcare",
            ads: 2,
            dailyBudget: 25,
          },
        ],
      },
    ],
  },
  audiences: {
    total: 3,
    inUse: 1,
    combinedReach: "~190K",
    list: [
      {
        id: "cvau1",
        type: "saved",
        name: "Medical travel — West Africa",
        description: "All · 30-60 · West Africa",
        detail: "Interests: medical travel, private healthcare",
        reach: "120K-160K",
        created: "Created 4 May",
        inUse: 1,
      },
      {
        id: "cvau2",
        type: "custom",
        name: "CVMI enquiry list",
        description: "Uploaded list · 380 matched on Meta",
        detail: "Refreshed 12 May",
        reach: "~380",
        created: "Created 30 Apr",
        inUse: 0,
      },
    ],
  },
  adPerformance: {
    spend: 560,
    spendTrend: "UP 4%",
    impressions: "39K",
    impressionsTrend: "UP 6%",
    clicks: "940",
    clicksTrend: "UP 9%",
    conversions: 18,
    conversionsTrend: "UP 11%",
    avgCpc: 0.61,
    avgCpcTrend: "UP 2%",
    series: {
      spend: [8, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32],
      conversions: [1, 2, 2, 3, 4, 5, 6, 8, 10, 12, 14, 16],
    },
    topAds: [
      { name: "Medical excellence — FB Feed", context: "Intl Patients · West Africa", spend: 240, ctr: "2.4%", cpc: 0.58, conv: 12 },
      { name: "Global standards — FB Feed", context: "Intl Patients · West Africa", spend: 180, ctr: "1.9%", cpc: 0.66, conv: 6 },
    ],
    insight:
      "CVMI underperforms relative to ad spend. Consider revisiting targeting or creative — current CPA is well above the group average.",
  },
  adSafety: {
    monthlyCap: 3000,
    usedThisMonth: 560,
    requireBudgetCap: true,
    confirmAiSpend: true,
    doubleConfirmThreshold: 500,
    dailyDigest: false,
    recentAudit: 'Younes created "International Patients — Awareness" · 4 May 09:20',
  },
};

export const COMPANY_DATA: Record<string, CompanyData> = {
  occ,
  tibok,
  cvmi,
};

export const ANALYTICS = {
  overview: {
    postsPublished: 87,
    postsTrend: "UP 14%",
    engagement: "4,820",
    engagementTrend: "UP 22%",
    adSpend: 4260,
    adSpendTrend: "UP 9%",
    conversions: 218,
    conversionsTrend: "UP 28%",
  },
  byCompany: [
    { name: "OCC", value: 2840, pct: 59, color: "#1e3a5f" },
    { name: "Tibok", value: 1420, pct: 30, color: "#6b1f3a" },
    { name: "CVMI", value: 560, pct: 11, color: "#166534" },
  ],
  byPlatform: [
    { name: "Facebook", value: 2640, max: 2640, color: "#1877f2", connected: true },
    { name: "Instagram", value: 2180, max: 2640, color: "#d62976", connected: true },
    { name: "LinkedIn", value: 0, max: 2640, color: "#0a66c2", connected: false },
  ],
  summary:
    'Strong month across all companies. OCC drove 59% of engagement and 70% of conversions, largely from "January Detox". Tibok grew 38% week-over-week. CVMI underperforms relative to ad spend — consider revisiting targeting or creative.',
};

export const TEAM = [
  { name: "Younes O.", email: "younes@ddsgroup.mu", role: "admin" },
  { name: "Sarah M.", email: "sarah@ddsgroup.mu", role: "editor" },
  { name: "Priya R.", email: "priya@ddsgroup.mu", role: "viewer" },
];
